#!/usr/bin/env bash
#Ensure Nginx runs as nginx user and listens on port 8080

# Create nginx user if it doesn't exist
id -u nginx &>/dev/null || adduser --system --no-create-home --shell /bin/false nginx

# Set user directive to nginx in config
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Restart nginx
nginx -t && service nginx restart

